services:
  frontend:
    build:
      context: ./frontend
    environment:
      BACKEND_API_URL: http://backend:8080
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    command: sh -c "go run ./cmd/seed && go run ./cmd/api"
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/firmware_practice?sslmode=disable
      REDIS_ADDR: redis:6379
      SUBMISSION_QUEUE: bitforge:submission:queue
      DEFAULT_USER_HANDLE: demo
      C_COMPILER: gcc
      COMPILE_TIMEOUT: 4s
      RUN_TIMEOUT: 2s
      QUEUE_POP_TIMEOUT: 4s

  worker:
    build:
      context: ./backend
    command: go run ./cmd/worker
    volumes:
      - ./backend:/app
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/firmware_practice?sslmode=disable
      REDIS_ADDR: redis:6379
      SUBMISSION_QUEUE: bitforge:submission:queue
      C_COMPILER: gcc
      COMPILE_TIMEOUT: 4s
      RUN_TIMEOUT: 2s
      QUEUE_POP_TIMEOUT: 4s

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: firmware_practice
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d firmware_practice"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
